"""
Critic Agent — self-evaluates plan quality and triggers replanning if needed.
Scores on feasibility, risk_coverage, and timeline_realism.
"""
import json
from gemini_client import generate

REPLAN_THRESHOLD = 6  # Minimum score to pass; below triggers replanning


def evaluate_plan(plan: dict, goal: str, domain: str) -> dict:
    """
    Evaluate a generated plan on three dimensions.

    Args:
        plan: The plan dict generated by the planner
        goal: Original user goal
        domain: Goal domain

    Returns:
        dict with scores, feedback, passed (bool), and improvement_hints
    """
    plan_str = json.dumps(plan, indent=2)

    prompt = f"""You are SHE-ORACLE's Critic Agent — a rigorous quality evaluator for AI-generated strategic plans for women empowerment.

Original Goal: {goal}
Domain: {domain}

Generated Plan:
{plan_str}

Evaluate this plan critically on THREE dimensions (score 1-10 each):

1. FEASIBILITY (1-10): Is this plan actually achievable given typical constraints of women in India? Are resources realistic? Is access to mentioned schemes/tools actually possible?

2. RISK_COVERAGE (1-10): Does the plan adequately identify and address risks? Are safety nets mentioned? Are failure scenarios considered?

3. TIMELINE_REALISM (1-10): Are the timelines realistic? Too optimistic? Does the sequencing make sense?

Return ONLY valid JSON:
{{
  "scores": {{
    "feasibility": 8,
    "risk_coverage": 7,
    "timeline_realism": 6
  }},
  "overall_score": 7,
  "passed": true,
  "strengths": [
    "What the plan does well"
  ],
  "weaknesses": [
    "What needs improvement"
  ],
  "improvement_hints": [
    "Specific instruction to improve the plan"
  ],
  "verdict": "APPROVED/NEEDS_REVISION/REJECTED",
  "verdict_reasoning": "2-3 sentence explanation"
}}

A plan PASSES if all three scores >= {REPLAN_THRESHOLD}. Set passed=true only if all scores are >= {REPLAN_THRESHOLD}."""

    text = generate(prompt)

    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()

    try:
        result = json.loads(text)
        # Ensure passed field is correctly set based on scores
        scores = result.get("scores", {})
        all_pass = all(
            scores.get(dim, 0) >= REPLAN_THRESHOLD
            for dim in ["feasibility", "risk_coverage", "timeline_realism"]
        )
        result["passed"] = all_pass
        return result
    except json.JSONDecodeError:
        return {
            "scores": {"feasibility": 7, "risk_coverage": 7, "timeline_realism": 7},
            "overall_score": 7,
            "passed": True,
            "strengths": [],
            "weaknesses": [],
            "improvement_hints": [],
            "verdict": "APPROVED",
            "verdict_reasoning": "Unable to parse critic response; defaulting to approved.",
        }
