import { useState } from "react";
import { Copy, Check, MessageCircle, Camera } from "lucide-react";

const levelColors = {
  LOW:      "text-green-400 bg-green-900/30 border-green-700/50",
  MODERATE: "text-yellow-400 bg-yellow-900/30 border-yellow-700/50",
  HIGH:     "text-orange-400 bg-orange-900/30 border-orange-700/50",
  CRITICAL: "text-red-400 bg-red-900/40 border-red-500/60",
};

function CopyButton({ text, label = "Copy" }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button
      onClick={handleCopy}
      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
        copied
          ? "bg-green-900/40 text-green-400 border border-green-700/40"
          : "bg-white/8 hover:bg-white/15 text-gray-300 hover:text-white border border-white/10"
      }`}
    >
      {copied ? <Check size={12} /> : <Copy size={12} />}
      {copied ? "Copied!" : label}
    </button>
  );
}

export default function EmergencySharePanel({ emergencyMessage, safetyCard }) {
  if (!emergencyMessage && !safetyCard) return null;

  const riskLevel = safetyCard?.risk_level || "MODERATE";
  const cardColorClass = levelColors[riskLevel] || levelColors.MODERATE;

  // Build the full card text for copying as screenshot-alternative
  const cardText = safetyCard
    ? [
        "═══ SHE-ORACLE SAFETY ALERT ═══",
        `Cab: ${safetyCard.ride_details}`,
        `Route: ${safetyCard.route}`,
        `Time: ${safetyCard.time}`,
        `Risk Level: ${safetyCard.risk_level}`,
        `Concern: ${safetyCard.key_concern}`,
        "────────────────────────────────",
        safetyCard.check_in_instruction,
        "Generated by SHE-ORACLE Safety System",
      ].join("\n")
    : "";

  return (
    <div className="space-y-4">
      {/* WhatsApp/SMS Message */}
      {emergencyMessage && (
        <div className="glass rounded-xl overflow-hidden border border-orange-800/30">
          <div className="flex items-center justify-between px-4 py-3 bg-orange-900/20 border-b border-orange-800/30">
            <div className="flex items-center gap-2">
              <MessageCircle size={14} className="text-orange-400" />
              <span className="text-xs font-semibold text-orange-300 uppercase tracking-wide">
                Emergency Message — Copy & Send Now
              </span>
            </div>
            <CopyButton text={emergencyMessage} label="Copy Message" />
          </div>
          <div className="px-4 py-4">
            <pre className="text-sm text-gray-200 whitespace-pre-wrap font-sans leading-relaxed">
              {emergencyMessage}
            </pre>
          </div>
        </div>
      )}

      {/* Safety Card */}
      {safetyCard && (
        <div className="glass rounded-xl overflow-hidden border border-red-800/40">
          <div className="flex items-center justify-between px-4 py-3 bg-red-900/20 border-b border-red-800/30">
            <div className="flex items-center gap-2">
              <Camera size={14} className="text-red-400" />
              <span className="text-xs font-semibold text-red-300 uppercase tracking-wide">
                Safety Card — Screenshot & Share
              </span>
            </div>
            <CopyButton text={cardText} label="Copy Card" />
          </div>

          {/* Card content — styled to look like a shareable card */}
          <div className="p-5">
            {/* Header */}
            <div className="text-center mb-4 pb-4 border-b border-red-800/30">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-red-900/40 border border-red-700/50 mb-2">
                <div className="w-2 h-2 rounded-full bg-red-400 animate-pulse" />
                <span className="text-xs font-bold text-red-300 tracking-widest">SHE-ORACLE SAFETY ALERT</span>
              </div>
              <div className={`inline-flex px-3 py-1 rounded-full border text-xs font-bold ${cardColorClass}`}>
                Risk Level: {safetyCard.risk_level}
              </div>
            </div>

            {/* Details grid */}
            <div className="space-y-2.5">
              <div className="flex gap-3">
                <span className="text-xs text-gray-500 w-16 flex-shrink-0 pt-0.5">Cab</span>
                <span className="text-sm text-white font-medium">{safetyCard.ride_details}</span>
              </div>
              <div className="flex gap-3">
                <span className="text-xs text-gray-500 w-16 flex-shrink-0 pt-0.5">Route</span>
                <span className="text-sm text-gray-200">{safetyCard.route}</span>
              </div>
              <div className="flex gap-3">
                <span className="text-xs text-gray-500 w-16 flex-shrink-0 pt-0.5">Time</span>
                <span className="text-sm text-gray-200">{safetyCard.time}</span>
              </div>
              <div className="flex gap-3">
                <span className="text-xs text-gray-500 w-16 flex-shrink-0 pt-0.5">Concern</span>
                <span className="text-sm text-orange-300">{safetyCard.key_concern}</span>
              </div>
            </div>

            {/* Check-in instruction */}
            <div className="mt-4 pt-4 border-t border-red-800/30">
              <p className="text-sm font-bold text-red-300 text-center leading-relaxed">
                {safetyCard.check_in_instruction}
              </p>
            </div>

            <p className="text-xs text-gray-600 text-center mt-3">
              Take a screenshot of this card and send to a trusted contact
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
